export const homeObjOne = {
    id: 'about',
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topLine: 'About',
    headline: "Who's this guy?",
    description: "I'm a Software Developer from Rome, always willing to learn new things. I have a serious passion for programming, game development and 3D modeling.",
    buttonLabel: '',
    imgStart: true,
    img: require('../../images/me.jpg'),
    alt: 'Me :)',
    dark: true,
    primary: true,
    darkText: false,
};

export const homeObjTwo = {
    id: 'contact',
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    topLine: 'Unlimited Access',
    headline: 'Unlimited Transaction with zero fees',
    description: 'Get access to our exclusive app that allows you to send unlimited transactions without getting charget any fees.',
    buttonLabel: 'Learn More',
    imgStart: true,
    img: require('../../images/svg-2.svg'),
    alt: 'Piggybank',
    dark: false,
    primary: false,
    darkText: true,
};